using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Reflection;
using FishUI.Controls;

namespace FishUI
{
	/// <summary>
	/// Generates C# designer code from a list of controls.
	/// Creates .Designer.cs files that implement IFishUIForm.
	/// </summary>
	public class DesignerCodeGenerator
	{
		private readonly FishCSharpWriter _writer;
		private readonly HashSet<string> _usedVariableNames = new HashSet<string>();
		private readonly Dictionary<Control, string> _controlVariableNames = new Dictionary<Control, string>();
		private int _anonymousCounter = 0;

		/// <summary>
		/// Creates a new designer code generator.
		/// </summary>
		public DesignerCodeGenerator()
		{
			_writer = new FishCSharpWriter();
		}

		/// <summary>
		/// Generates a .Designer.cs file from the given controls.
		/// </summary>
		/// <param name="controls">The root-level controls to generate code for.</param>
		/// <param name="namespaceName">The namespace for the generated class.</param>
		/// <param name="className">The class name for the generated form.</param>
		/// <returns>The generated C# code as a string.</returns>
		public string Generate(IEnumerable<Control> controls, string namespaceName, string className)
		{
			_writer.Clear();
			_usedVariableNames.Clear();
			_controlVariableNames.Clear();
			_anonymousCounter = 0;

			// First pass: assign variable names to all controls
			foreach (var control in controls)
			{
				AssignVariableNames(control);
			}

			// Write file header
			_writer.WriteComment("------------------------------------------------------------------------------");
			_writer.WriteComment(" <auto-generated>");
			_writer.WriteComment("     This code was generated by FishUI Layout Editor.");
			_writer.WriteComment("     Changes to this file may be overwritten when regenerating.");
			_writer.WriteComment(" </auto-generated>");
			_writer.WriteComment("------------------------------------------------------------------------------");
			_writer.WriteLine();

			// Write using statements
			_writer.WriteUsings(
				"System",
				"System.Numerics",
				"FishUI",
				"FishUI.Controls"
			);
			_writer.WriteLine();

			// Begin namespace
			_writer.BeginNamespace(namespaceName);

			// Begin partial class
			_writer.WriteSummary($"Designer-generated form class for {className}.");
			_writer.BeginClass(className, "IFishUIForm", isPartial: true);

			// Generate field declarations for controls with IDs
			GenerateFieldDeclarations(controls);
			_writer.WriteLine();

			// Generate Init method
			GenerateInitMethod();
			_writer.WriteLine();

			// Generate LoadControls method
			GenerateLoadControlsMethod(controls);
			_writer.WriteLine();

			// Generate OnLoaded method
			GenerateOnLoadedMethod();

			// End class and namespace
			_writer.EndClass();
			_writer.EndNamespace();

			return _writer.Code;
		}

		private void GenerateFieldDeclarations(IEnumerable<Control> controls)
		{
			_writer.BeginRegion("Control Fields");
			_writer.WriteLine();

			foreach (var control in controls)
			{
				GenerateFieldDeclaration(control);
			}

			_writer.WriteLine();
			_writer.EndRegion();
		}

		private void GenerateFieldDeclaration(Control control)
		{
			string varName = GetVariableName(control);
			string typeName = control.GetType().Name;

			_writer.WriteSummary($"The {typeName} control{(string.IsNullOrEmpty(control.ID) ? "" : $" ({control.ID})")}.");
			_writer.WriteField(typeName, varName, "protected");

			// Recursively generate for children
			var children = GetSerializableChildren(control);
			foreach (var child in children)
			{
				GenerateFieldDeclaration(child);
			}
		}

		private void GenerateInitMethod()
		{
			_writer.WriteSummary("Initializes the FishUI instance with settings.");
			_writer.BeginMethod("void", "Init", "FishUISettings UISettings, IFishUIGfx Gfx, IFishUIInput Input, IFishUIEvents Events");
			_writer.WriteComment("Override this method to customize FishUI initialization");
			_writer.EndMethod();
		}

		private void GenerateLoadControlsMethod(IEnumerable<Control> controls)
		{
			_writer.WriteSummary("Creates and configures all controls, adding them to the FishUI instance.");
			// Use FishUI.FishUI to disambiguate from namespace
			_writer.BeginMethod("void", "LoadControls", "FishUI.FishUI FUI");

			foreach (var control in controls)
			{
				GenerateControlCreation(control, null);
				_writer.WriteLine();
			}

			// Add root controls to FUI
			_writer.WriteComment("Add root controls to FishUI");
			foreach (var control in controls)
			{
				string varName = GetVariableName(control);
				_writer.WriteLine($"FUI.AddControl({varName});");
			}

			_writer.EndMethod();
		}

		private void GenerateControlCreation(Control control, string parentVarName)
		{
			string varName = GetVariableName(control);
			string typeName = control.GetType().Name;

			_writer.WriteComment($"Create {typeName}");
			_writer.WriteLine($"{varName} = new {typeName}();");

			// Generate property assignments
			GeneratePropertyAssignments(control, varName);

			// Handle children
			var children = GetSerializableChildren(control);
			foreach (var child in children)
			{
				_writer.WriteLine();
				GenerateControlCreation(child, varName);
			}

			// Add children to parent
			if (children.Any())
			{
				_writer.WriteLine();
				_writer.WriteComment($"Add children to {varName}");
				foreach (var child in children)
				{
					string childVarName = GetVariableName(child);

					// Use appropriate AddChild method
					if (control is Window)
					{
						_writer.WriteLine($"((Window){varName}).AddChild({childVarName});");
					}
					else
					{
						_writer.WriteLine($"{varName}.AddChild({childVarName});");
					}
				}
			}

			// Handle special cases
			GenerateSpecialCases(control, varName);
		}

		private void GeneratePropertyAssignments(Control control, string varName)
		{
			Type type = control.GetType();

			// Position
			if (control.Position.X != 0 || control.Position.Y != 0)
			{
				_writer.WriteLine($"{varName}.Position = {FishCSharpWriter.Vector2Literal(new Vector2(control.Position.X, control.Position.Y))};");
			}

			// Size
			if (control.Size != Vector2.Zero)
			{
				_writer.WriteLine($"{varName}.Size = {FishCSharpWriter.Vector2Literal(control.Size)};");
			}

			// ID
			if (!string.IsNullOrEmpty(control.ID))
			{
				_writer.WriteLine($"{varName}.ID = {FishCSharpWriter.StringLiteral(control.ID)};");
			}

			// Anchor (if not default TopLeft)
			if (control.Anchor != FishUIAnchor.TopLeft)
			{
				_writer.WriteLine($"{varName}.Anchor = {FishCSharpWriter.EnumLiteral(control.Anchor)};");
			}

			// AnchorParentSize (if set)
			if (control.AnchorParentSize != Vector2.Zero)
			{
				_writer.WriteLine($"{varName}.AnchorParentSize = {FishCSharpWriter.Vector2Literal(control.AnchorParentSize)};");
			}

			// Visible (if false)
			if (!control.Visible)
			{
				_writer.WriteLine($"{varName}.Visible = false;");
			}

			// Type-specific properties
			GenerateTypeSpecificProperties(control, varName);
		}

		private void GenerateTypeSpecificProperties(Control control, string varName)
		{
			switch (control)
			{
				case Button btn:
					if (!string.IsNullOrEmpty(btn.Text))
						_writer.WriteLine($"{varName}.Text = {FishCSharpWriter.StringLiteral(btn.Text)};");
					if (btn.IsToggleButton)
						_writer.WriteLine($"{varName}.IsToggleButton = true;");
					if (btn.IsRepeatButton)
						_writer.WriteLine($"{varName}.IsRepeatButton = true;");
					break;

				case Label lbl:
					if (!string.IsNullOrEmpty(lbl.Text))
						_writer.WriteLine($"{varName}.Text = {FishCSharpWriter.StringLiteral(lbl.Text)};");
					if (lbl.Alignment != Align.Left)
						_writer.WriteLine($"{varName}.Alignment = {FishCSharpWriter.EnumLiteral(lbl.Alignment)};");
					break;

				case Textbox txt:
					if (!string.IsNullOrEmpty(txt.Text))
						_writer.WriteLine($"{varName}.Text = {FishCSharpWriter.StringLiteral(txt.Text)};");
					if (!string.IsNullOrEmpty(txt.Placeholder))
						_writer.WriteLine($"{varName}.Placeholder = {FishCSharpWriter.StringLiteral(txt.Placeholder)};");
					break;

				case CheckBox chk:
					if (chk.IsChecked)
						_writer.WriteLine($"{varName}.IsChecked = true;");
					break;

				case RadioButton rb:
					if (rb.IsChecked)
						_writer.WriteLine($"{varName}.IsChecked = true;");
					break;

				case Panel panel:
					if (panel.IsTransparent)
						_writer.WriteLine($"{varName}.IsTransparent = true;");
					if (panel.Variant != PanelVariant.Normal)
						_writer.WriteLine($"{varName}.Variant = {FishCSharpWriter.EnumLiteral(panel.Variant)};");
					if (panel.BorderStyle != BorderStyle.None)
						_writer.WriteLine($"{varName}.BorderStyle = {FishCSharpWriter.EnumLiteral(panel.BorderStyle)};");
					break;

				case Window window:
					if (!string.IsNullOrEmpty(window.Title) && window.Title != "Window")
						_writer.WriteLine($"{varName}.Title = {FishCSharpWriter.StringLiteral(window.Title)};");
					if (!window.IsResizable)
						_writer.WriteLine($"{varName}.IsResizable = false;");
					if (!window.ShowCloseButton)
						_writer.WriteLine($"{varName}.ShowCloseButton = false;");
					if (!window.ShowShadow)
						_writer.WriteLine($"{varName}.ShowShadow = false;");
					break;

				case GroupBox grp:
					if (!string.IsNullOrEmpty(grp.Text) && grp.Text != "Group")
						_writer.WriteLine($"{varName}.Text = {FishCSharpWriter.StringLiteral(grp.Text)};");
					break;

				case ProgressBar pb:
					if (pb.Value != 0)
						_writer.WriteLine($"{varName}.Value = {FishCSharpWriter.FloatLiteral(pb.Value)};");
					break;

				case Slider slider:
					if (slider.Value != 0)
						_writer.WriteLine($"{varName}.Value = {FishCSharpWriter.FloatLiteral(slider.Value)};");
					if (slider.MinValue != 0)
						_writer.WriteLine($"{varName}.MinValue = {FishCSharpWriter.FloatLiteral(slider.MinValue)};");
					if (slider.MaxValue != 100)
						_writer.WriteLine($"{varName}.MaxValue = {FishCSharpWriter.FloatLiteral(slider.MaxValue)};");
					break;

				case ToggleSwitch ts:
					if (ts.IsOn)
						_writer.WriteLine($"{varName}.IsOn = true;");
					break;

				case NumericUpDown nud:
					if (nud.Value != 0)
						_writer.WriteLine($"{varName}.Value = {FishCSharpWriter.FloatLiteral(nud.Value)};");
					if (nud.MinValue != 0)
						_writer.WriteLine($"{varName}.MinValue = {FishCSharpWriter.FloatLiteral(nud.MinValue)};");
					if (nud.MaxValue != 100)
						_writer.WriteLine($"{varName}.MaxValue = {FishCSharpWriter.FloatLiteral(nud.MaxValue)};");
					if (nud.Step != 1)
						_writer.WriteLine($"{varName}.Step = {FishCSharpWriter.FloatLiteral(nud.Step)};");
					break;

				case ImageBox img:
					if (!string.IsNullOrEmpty(img.ImagePath))
						_writer.WriteLine($"{varName}.ImagePath = {FishCSharpWriter.StringLiteral(img.ImagePath)};");
					if (img.FilterMode == ImageFilterMode.Pixelated)
						_writer.WriteLine($"{varName}.FilterMode = ImageFilterMode.Pixelated;");
					break;

				case StaticText st:
					if (!string.IsNullOrEmpty(st.Text))
						_writer.WriteLine($"{varName}.Text = {FishCSharpWriter.StringLiteral(st.Text)};");
					break;

				case BarGauge bg:
					if (bg.Value != 0)
						_writer.WriteLine($"{varName}.Value = {FishCSharpWriter.FloatLiteral(bg.Value)};");
					break;

				case RadialGauge rg:
					if (rg.Value != 0)
						_writer.WriteLine($"{varName}.Value = {FishCSharpWriter.FloatLiteral(rg.Value)};");
					break;
			}
		}

		private void GenerateSpecialCases(Control control, string varName)
		{
			switch (control)
			{
				case ListBox lb when lb.Items.Count > 0:
					_writer.WriteLine();
					_writer.WriteComment("Add ListBox items");
					foreach (var item in lb.Items)
					{
						_writer.WriteLine($"{varName}.AddItem({FishCSharpWriter.StringLiteral(item.Text)});");
					}
					break;

				case DropDown dd when dd.Items.Count > 0:
					_writer.WriteLine();
					_writer.WriteComment("Add DropDown items");
					foreach (var item in dd.Items)
					{
						_writer.WriteLine($"{varName}.AddItem({FishCSharpWriter.StringLiteral(item.Text)});");
					}
					break;

				case TabControl tc when tc.TabPages.Count > 0:
					_writer.WriteLine();
					_writer.WriteComment("Add TabControl tabs");
					foreach (var tab in tc.TabPages)
					{
						_writer.WriteLine($"{varName}.AddTab({FishCSharpWriter.StringLiteral(tab.Text)});");
					}
					break;

				case DataGrid dg when dg.Columns.Count > 0:
					_writer.WriteLine();
					_writer.WriteComment("Add DataGrid columns");
					foreach (var col in dg.Columns)
					{
						_writer.WriteLine($"{varName}.AddColumn({FishCSharpWriter.StringLiteral(col.Header)}, {FishCSharpWriter.FloatLiteral(col.Width)});");
					}
					break;
			}
		}

		private void GenerateOnLoadedMethod()
		{
			_writer.WriteSummary("Called after all controls have been loaded. Override to add event handlers and custom logic.");
			_writer.BeginMethod("void", "OnLoaded", "", "public", isVirtual: true);
			_writer.WriteComment("Override this method to add event handlers and post-load logic");
			_writer.EndMethod();
		}

		/// <summary>
		/// Recursively assigns variable names to all controls before code generation.
		/// This ensures consistent variable names throughout the generated code.
		/// </summary>
		private void AssignVariableNames(Control control)
		{
			// Generate and cache variable name for this control
			string varName = GenerateVariableName(control);
			_controlVariableNames[control] = varName;

			// Recursively assign for children
			var children = GetSerializableChildren(control);
			foreach (var child in children)
			{
				AssignVariableNames(child);
			}
		}

		/// <summary>
		/// Generates a unique variable name for a control.
		/// Priority: DesignerName > ID > auto-generated name based on type.
		/// </summary>
		private string GenerateVariableName(Control control)
		{
			// If control has a DesignerName, try to use it as the variable name
			if (!string.IsNullOrEmpty(control.DesignerName))
			{
				string varName = SanitizeIdentifier(control.DesignerName);
				if (!_usedVariableNames.Contains(varName))
				{
					_usedVariableNames.Add(varName);
					return varName;
				}
			}

			// Fall back to ID if DesignerName is not set
			if (!string.IsNullOrEmpty(control.ID))
			{
				string varName = SanitizeIdentifier(control.ID);
				if (!_usedVariableNames.Contains(varName))
				{
					_usedVariableNames.Add(varName);
					return varName;
				}
			}

			// Generate anonymous variable name based on control type
			string typeName = control.GetType().Name;
			string baseName = char.ToLower(typeName[0]) + typeName.Substring(1);

			string result;
			do
			{
				_anonymousCounter++;
				result = $"{baseName}{_anonymousCounter}";
			}
			while (_usedVariableNames.Contains(result));

			_usedVariableNames.Add(result);
			return result;
		}

		/// <summary>
		/// Gets the cached variable name for a control.
		/// </summary>
		private string GetVariableName(Control control)
		{
			if (_controlVariableNames.TryGetValue(control, out string varName))
			{
				return varName;
			}

			// Fallback (should not happen if AssignVariableNames was called first)
			return GenerateVariableName(control);
		}

		private string SanitizeIdentifier(string name)
		{
			if (string.IsNullOrEmpty(name))
				return "_control";

			// Replace invalid characters with underscores
			var sb = new System.Text.StringBuilder();
			for (int i = 0; i < name.Length; i++)
			{
				char c = name[i];
				if (i == 0)
				{
					if (char.IsLetter(c) || c == '_')
						sb.Append(c);
					else
						sb.Append('_');
				}
				else
				{
					if (char.IsLetterOrDigit(c) || c == '_')
						sb.Append(c);
					else
						sb.Append('_');
				}
			}

			string result = sb.ToString();

			// Ensure it doesn't start with a number
			if (result.Length > 0 && char.IsDigit(result[0]))
				result = "_" + result;

			return result;
		}

		private IEnumerable<Control> GetSerializableChildren(Control control)
		{
			// For Window, use ContentChildren to get user-added children only
			if (control is Window window)
			{
				return window.ContentChildren;
			}

			// For other controls, use Children but filter out internal controls
			return control.Children.Where(c => !IsInternalControl(c));
		}

		private bool IsInternalControl(Control control)
		{
			// Filter out internal controls that are auto-created
			return control is Titlebar ||
				   (control is Panel p && p.IsTransparent && control.GetParent() is Window);
		}
	}
}
