using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Reflection;
using FishUI.Controls;

namespace FishUI
{
    /// <summary>
    /// Generates C# designer code from a list of controls.
    /// Creates .Designer.cs files that implement IFishUIForm.
    /// </summary>
    public class DesignerCodeGenerator
    {
        private static readonly HashSet<string> Keywords = new HashSet<string>((
            "abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while").Split(' '));
        private readonly FishCSharpWriter _writer;
        private readonly HashSet<string> _usedVariableNames = new HashSet<string>();
        private readonly Dictionary<Control, string> _controlVariableNames = new Dictionary<Control, string>();
        private int _anonymousCounter = 0;

        /// <summary>
        /// Creates a new designer code generator.
        /// </summary>
        public DesignerCodeGenerator()
        {
            _writer = new FishCSharpWriter();
        }

        /// <summary>
        /// Generates a .Designer.cs file from the given controls.
        /// </summary>
        /// <param name="controls">The root-level controls to generate code for.</param>
        /// <param name="namespaceName">The namespace for the generated class.</param>
        /// <param name="className">The class name for the generated form.</param>
        /// <returns>The generated C# code as a string.</returns>
        public string Generate(IEnumerable<Control> controls, string namespaceName, string className)
        {
            if (controls == null) throw new ArgumentNullException(nameof(controls));
            controls = controls.ToArray();
            _writer.Clear();
            _usedVariableNames.Clear();
            _controlVariableNames.Clear();
            _anonymousCounter = 0;
            _usedVariableNames.UnionWith(new[] { className, "FUI", "Init", "LoadControls", "OnLoaded" });

            // First pass: assign variable names to all controls
            foreach (var control in controls)
            {
                AssignVariableNames(control);
            }

            // Write file header
            _writer.WriteComment("------------------------------------------------------------------------------");
            _writer.WriteComment(" <auto-generated>");
            _writer.WriteComment("     This code was generated by FishUI Layout Editor.");
            _writer.WriteComment("     Changes to this file may be overwritten when regenerating.");
            _writer.WriteComment(" </auto-generated>");
            _writer.WriteComment("------------------------------------------------------------------------------");
            _writer.WriteLine();

            // Write using statements
            _writer.WriteUsings(
                "System",
                "System.Numerics",
                "FishUI",
                "FishUI.Controls"
            );
            _writer.WriteLine();

            // Begin namespace
            _writer.BeginNamespace(namespaceName);

            // Begin partial class
            _writer.WriteSummary($"Designer-generated form class for {className}.");
            _writer.BeginClass(className, "IFishUIForm", isPartial: true);

            // Generate field declarations for controls with IDs
            GenerateFieldDeclarations(controls);
            _writer.WriteLine();

            // Generate Init method
            GenerateInitMethod();
            _writer.WriteLine();

            // Generate LoadControls method
            GenerateLoadControlsMethod(controls);
            _writer.WriteLine();

            // Generate OnLoaded method
            GenerateOnLoadedMethod();

            // End class and namespace
            _writer.EndClass();
            _writer.EndNamespace();

            return _writer.Code;
        }

        private void GenerateFieldDeclarations(IEnumerable<Control> controls)
        {
            _writer.BeginRegion("Control Fields");
            _writer.WriteLine();

            foreach (var control in controls)
            {
                GenerateFieldDeclaration(control);
            }

            _writer.WriteLine();
            _writer.EndRegion();
        }

        private void GenerateFieldDeclaration(Control control)
        {
            string varName = GetVariableName(control);
            string typeName = control.GetType().Name;

            _writer.WriteSummary($"The {typeName} control{(string.IsNullOrEmpty(control.ID) ? "" : $" ({control.ID})")}.");
            _writer.WriteField(typeName, varName, "protected");

            // Recursively generate for children
            var children = GetSerializableChildren(control);
            foreach (var child in children)
            {
                GenerateFieldDeclaration(child);
            }
        }

        private void GenerateInitMethod()
        {
            _writer.WriteSummary("Initializes the FishUI instance with settings.");
            _writer.BeginMethod("void", "Init", "FishUISettings UISettings, IFishUIGfx Gfx, IFishUIInput Input, IFishUIEvents Events");
            _writer.WriteComment("Override this method to customize FishUI initialization");
            _writer.EndMethod();
        }

        private void GenerateLoadControlsMethod(IEnumerable<Control> controls)
        {
            _writer.WriteSummary("Creates and configures all controls, adding them to the FishUI instance.");
            // Use FishUI.FishUI to disambiguate from namespace
            _writer.BeginMethod("void", "LoadControls", "FishUI.FishUI FUI");

            foreach (var control in controls)
            {
                GenerateControlCreation(control, null);
                _writer.WriteLine();
            }

            // Add root controls to FUI
            _writer.WriteComment("Add root controls to FishUI");
            foreach (var control in controls)
            {
                string varName = GetVariableName(control);
                _writer.WriteLine($"{varName}.OnDeserialized(FUI);");
                _writer.WriteLine($"FUI.AddControl({varName});");
                _writer.WriteLine($"{varName}.ZDepth = {control.ZDepth};");
            }

            _writer.EndMethod();
        }

        private void GenerateControlCreation(Control control, string parentVarName)
        {
            string varName = GetVariableName(control);
            string typeName = control.GetType().Name;

            _writer.WriteComment($"Create {typeName}");
            _writer.WriteLine($"{varName} = new {typeName}();");

            // Generate property assignments
            GeneratePropertyAssignments(control, varName);

            // Handle children
            var children = GetSerializableChildren(control);
            foreach (var child in children)
            {
                _writer.WriteLine();
                GenerateControlCreation(child, varName);
            }

            // Add children to parent
            if (children.Any())
            {
                _writer.WriteLine();
                _writer.WriteComment($"Add children to {varName}");
                foreach (var child in children)
                {
                    string childVarName = GetVariableName(child);

                    // Use appropriate AddChild method
                    if (control is Window)
                    {
                        _writer.WriteLine($"((Window){varName}).AddChild({childVarName});");
                    }
                    else if (control is TabControl tabs && child is Panel content)
                    {
                        var page = tabs.TabPages.FirstOrDefault(p => p.Content == content);
                        _writer.WriteLine($"{varName}.AddTab(new TabPage({FishCSharpWriter.StringLiteral(page?.Text ?? "Tab")}, {childVarName}) {{ Enabled = {(page?.Enabled != false ? "true" : "false")} }});");
                    }
                    else
                    {
                        _writer.WriteLine($"{varName}.AddChild({childVarName});");
                    }
                }
            }

            // Handle special cases
            GenerateSpecialCases(control, varName);

        }

        private readonly PersistedState _persisted = new PersistedState();

        private void GeneratePropertyAssignments(Control control, string varName)
        {
            if (control is IFishUINumericRange range)
                _writer.WriteLine($"{varName}.SetRange({FishCSharpWriter.FloatLiteral(range.MinValue)}, {FishCSharpWriter.FloatLiteral(range.MaxValue)});");
            foreach (var member in _persisted.Members(control))
            {
                string name = member.Name;
                if (name == "Children" || name == "UserChildren" || name == "ZDepth" || name == "SelectedIndex" ||
                    (control is TabControl && (name == "TabNames" || name == "TabEnabled")) ||
                    (control is IFishUINumericRange && (name == "MinValue" || name == "MaxValue"))) continue;
                string publicName = PersistedState.MemberName(control.GetType(), name);
                _writer.WriteLine($"{varName}.{publicName} = {_persisted.Literal(member.Read(control).Value, control.GetType().Name + "." + name)};");
            }
        }

        private void GenerateSpecialCases(Control control, string varName)
        {
            if (control is TabControl tabs)
            {
                _writer.WriteLine($"{varName}.TabNames = {_persisted.Literal(tabs.TabNames, "TabNames")};");
                _writer.WriteLine($"{varName}.TabEnabled = {_persisted.Literal(tabs.TabEnabled, "TabEnabled")};");
                _writer.WriteLine($"{varName}.SelectedIndex = {tabs.SelectedIndex};");
            }
            else if (control is ListBox list)
                _writer.WriteLine($"{varName}.SerializedSelectedIndex = {list.SelectedIndex};");
            else if (control is DropDown drop && drop.SelectedIndex >= 0)
                _writer.WriteLine($"{varName}.SelectIndex({drop.SelectedIndex});");
            // Children must be attached before restoring their explicit ordering.
            foreach (var child in GetSerializableChildren(control))
                _writer.WriteLine($"{GetVariableName(child)}.ZDepth = {child.ZDepth};");
        }

        private void GenerateOnLoadedMethod()
        {
            _writer.WriteSummary("Called after all controls have been loaded. Override to add event handlers and custom logic.");
            _writer.BeginMethod("void", "OnLoaded", "", "public", isVirtual: true);
            _writer.WriteComment("Override this method to add event handlers and post-load logic");
            _writer.EndMethod();
        }

        /// <summary>
        /// Recursively assigns variable names to all controls before code generation.
        /// This ensures consistent variable names throughout the generated code.
        /// </summary>
        private void AssignVariableNames(Control control)
        {
            // Generate and cache variable name for this control
            string varName = GenerateVariableName(control);
            _controlVariableNames[control] = varName;

            // Recursively assign for children
            var children = GetSerializableChildren(control);
            foreach (var child in children)
            {
                AssignVariableNames(child);
            }
        }

        /// <summary>
        /// Generates a unique variable name for a control.
        /// Priority: DesignerName > ID > auto-generated name based on type.
        /// </summary>
        private string GenerateVariableName(Control control)
        {
            // If control has a DesignerName, try to use it as the variable name
            if (!string.IsNullOrEmpty(control.DesignerName))
            {
                string varName = SanitizeIdentifier(control.DesignerName);
                if (!_usedVariableNames.Contains(varName))
                {
                    _usedVariableNames.Add(varName);
                    return varName;
                }
            }

            // Fall back to ID if DesignerName is not set
            if (!string.IsNullOrEmpty(control.ID))
            {
                string varName = SanitizeIdentifier(control.ID);
                if (!_usedVariableNames.Contains(varName))
                {
                    _usedVariableNames.Add(varName);
                    return varName;
                }
            }

            // Generate anonymous variable name based on control type
            string typeName = control.GetType().Name;
            string baseName = char.ToLower(typeName[0]) + typeName.Substring(1);

            string result;
            do
            {
                _anonymousCounter++;
                result = $"{baseName}{_anonymousCounter}";
            }
            while (_usedVariableNames.Contains(result));

            _usedVariableNames.Add(result);
            return result;
        }

        /// <summary>
        /// Gets the cached variable name for a control.
        /// </summary>
        private string GetVariableName(Control control)
        {
            if (_controlVariableNames.TryGetValue(control, out string varName))
            {
                return varName;
            }

            // Fallback (should not happen if AssignVariableNames was called first)
            return GenerateVariableName(control);
        }

        private string SanitizeIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return "_control";

            // Replace invalid characters with underscores
            var sb = new System.Text.StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                if (i == 0)
                {
                    if (char.IsLetter(c) || c == '_')
                        sb.Append(c);
                    else
                        sb.Append('_');
                }
                else
                {
                    if (char.IsLetterOrDigit(c) || c == '_')
                        sb.Append(c);
                    else
                        sb.Append('_');
                }
            }

            string result = sb.ToString();

            // Ensure it doesn't start with a number
            if (result.Length > 0 && char.IsDigit(result[0]))
                result = "_" + result;

            return Keywords.Contains(result) ? "@" + result : result;
        }

        private IEnumerable<Control> GetSerializableChildren(Control control)
        {
            // For Window, use ContentChildren to get user-added children only
            if (control is Window window)
            {
                return window.ContentChildren;
            }

            // For other controls, use Children but filter out internal controls
            return control.Children.Where(c => !IsInternalControl(c));
        }

        private bool IsInternalControl(Control control)
        {
            // Filter out internal controls that are auto-created
            return control.IsRuntimeChild || control is Titlebar ||
                   (control is Panel p && p.IsTransparent && control.GetParent() is Window);
        }
    }
}
