using System;

namespace FishUI
{
	/// <summary>
	/// Base interface for FishUI designer-generated form classes.
	/// Implement this interface to create forms that can be loaded from .Designer.cs files
	/// generated by the FishUI Layout Editor.
	/// </summary>
	/// <remarks>
	/// <para>
	/// The typical usage pattern is:
	/// <code>
	/// // Create an instance of your designer-generated form
	/// IFishUIForm form = new MyForm();
	/// 
	/// // Load all controls into the FishUI instance
	/// form.LoadControls(fishUI);
	/// 
	/// // Trigger post-load setup (event handlers, etc.)
	/// form.OnLoaded();
	/// </code>
	/// </para>
	/// <para>
	/// Forms are typically split into two partial class files:
	/// <list type="bullet">
	/// <item><description>MyForm.Designer.cs - Auto-generated control creation code</description></item>
	/// <item><description>MyForm.cs - User code with event handlers and custom logic</description></item>
	/// </list>
	/// </para>
	/// </remarks>
	/// <example>
	/// <code>
	/// public partial class MainForm : IFishUIForm
	/// {
	///     // Designer.cs provides: control fields, Init, LoadControls
	///     
	///     // User code overrides OnLoaded for event handlers
	///     public override void OnLoaded()
	///     {
	///         btnSubmit.OnButtonPressed += OnSubmitClicked;
	///     }
	/// }
	/// </code>
	/// </example>
	public interface IFishUIForm
	{
		/// <summary>
		/// Initializes the FishUI instance with the provided settings and backends.
		/// </summary>
		/// <remarks>
		/// Override this method to customize FishUI initialization, such as loading
		/// a custom theme or configuring UI scale. The default generated implementation
		/// is empty, leaving initialization to the calling code.
		/// </remarks>
		/// <param name="UISettings">UI settings including theme and scale.</param>
		/// <param name="Gfx">Graphics backend for rendering.</param>
		/// <param name="Input">Input backend for mouse/keyboard.</param>
		/// <param name="Events">Event handler for UI events.</param>
		void Init(FishUISettings UISettings, IFishUIGfx Gfx, IFishUIInput Input, IFishUIEvents Events);

		/// <summary>
		/// Creates all controls defined in the form and adds them to the FishUI instance.
		/// </summary>
		/// <remarks>
		/// This method is auto-generated by the FishUI Layout Editor's "Export as C#" feature.
		/// It creates control instances, sets their properties, establishes parent-child
		/// relationships, and adds root controls to the FishUI instance.
		/// </remarks>
		/// <param name="FUI">The FishUI instance to add controls to.</param>
		void LoadControls(FishUI FUI);

		/// <summary>
		/// Called after all controls have been loaded and added to the form.
		/// </summary>
		/// <remarks>
		/// Override this method in your user code partial class to:
		/// <list type="bullet">
		/// <item><description>Wire up event handlers (OnButtonPressed, OnValueChanged, etc.)</description></item>
		/// <item><description>Initialize control data (populate listboxes, set initial values)</description></item>
		/// <item><description>Perform any post-load setup that requires controls to exist</description></item>
		/// </list>
		/// </remarks>
		void OnLoaded();
	}
}
