// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by FishUI Layout Editor.
//      Changes to this file may be overwritten when regenerating.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Numerics;
using FishUI;
using FishUI.Controls;

namespace FishUIDemos.Forms
{
	/// <summary>
	/// Designer-generated form class for DemoForm.
	/// </summary>
	public partial class DemoForm : IFishUIForm
	{
		#region Control Fields

		/// <summary>
		/// The main Window control.
		/// </summary>
		protected Window mainWindow;

		/// <summary>
		/// The greeting Label control.
		/// </summary>
		protected Label lblGreeting;

		/// <summary>
		/// The name input Textbox control.
		/// </summary>
		protected Textbox txtName;

		/// <summary>
		/// The greet Button control.
		/// </summary>
		protected Button btnGreet;

		/// <summary>
		/// The close Button control.
		/// </summary>
		protected Button btnClose;

		#endregion

		/// <summary>
		/// Initializes the FishUI instance with settings.
		/// </summary>
		public void Init(FishUISettings UISettings, IFishUIGfx Gfx, IFishUIInput Input, IFishUIEvents Events)
		{
			// Override this method to customize FishUI initialization
		}

		/// <summary>
		/// Creates and configures all controls, adding them to the FishUI instance.
		/// </summary>
		public void LoadControls(FishUI.FishUI FUI)
		{
			// Create Window
			mainWindow = new Window();
			mainWindow.Position = new Vector2(200f, 100f);
			mainWindow.Size = new Vector2(400f, 250f);
			mainWindow.Title = "Demo Form";

			// Create greeting Label
			lblGreeting = new Label();
			lblGreeting.Position = new Vector2(20f, 20f);
			lblGreeting.Size = new Vector2(360f, 24f);
			lblGreeting.Text = "Enter your name:";

			// Create name Textbox
			txtName = new Textbox();
			txtName.Position = new Vector2(20f, 50f);
			txtName.Size = new Vector2(360f, 28f);
			txtName.Placeholder = "Your name here...";

			// Create greet Button
			btnGreet = new Button();
			btnGreet.Position = new Vector2(20f, 90f);
			btnGreet.Size = new Vector2(170f, 36f);
			btnGreet.Text = "Greet Me!";

			// Create close Button
			btnClose = new Button();
			btnClose.Position = new Vector2(210f, 90f);
			btnClose.Size = new Vector2(170f, 36f);
			btnClose.Text = "Close";

			// Add children to mainWindow
			((Window)mainWindow).AddChild(lblGreeting);
			((Window)mainWindow).AddChild(txtName);
			((Window)mainWindow).AddChild(btnGreet);
			((Window)mainWindow).AddChild(btnClose);

			// Add root controls to FishUI
			FUI.AddControl(mainWindow);
		}

		/// <summary>
		/// Called after all controls have been loaded. Override to add event handlers and custom logic.
		/// </summary>
		public virtual void OnLoaded()
		{
		}
	}
}
