// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by FishUI Layout Editor.
//      Changes to this file may be overwritten when regenerating.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Numerics;
using FishUI;
using FishUI.Controls;

namespace MyApp.Forms
{
	/// <summary>
	/// Designer-generated form class for MainForm.
	/// </summary>
	public partial class MainForm : IFishUIForm
	{
		#region Control Fields

		/// <summary>
		/// The Window control.
		/// </summary>
		protected Window window1;
		/// <summary>
		/// The Button control.
		/// </summary>
		protected Button button2;

		#endregion

		/// <summary>
		/// Initializes the FishUI instance with settings.
		/// </summary>
		public void Init(FishUISettings UISettings, IFishUIGfx Gfx, IFishUIInput Input, IFishUIEvents Events)
		{
			// Override this method to customize FishUI initialization
		}

		/// <summary>
		/// Creates and configures all controls, adding them to the FishUI instance.
		/// </summary>
		public void LoadControls(FishUI.FishUI FUI)
		{
			// Create Window
			window1 = new Window();
			window1.Position = new Vector2(128f, 112f);
			window1.Size = new Vector2(320f, 224f);

			// Create Button
			button2 = new Button();
			button2.Position = new Vector2(64f, 48f);
			button2.Size = new Vector2(160f, 96f);
			button2.Anchor = FishUIAnchor.All;
			button2.AnchorParentSize = new Vector2(308f, 194f);
			button2.Text = "Button";

			// Add children to window1
			((Window)window1).AddChild(button2);

			// Add root controls to FishUI
			FUI.AddControl(window1);
		}

		/// <summary>
		/// Called after all controls have been loaded. Override to add event handlers and custom logic.
		/// </summary>
		public virtual void OnLoaded()
		{
			// Override this method to add event handlers and post-load logic
		}
	}
}
