// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by FishUI Layout Editor.
//      Changes to this file may be overwritten when regenerating.
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Numerics;
using FishUI;
using FishUI.Controls;

namespace MyApp.Forms
{
	/// <summary>
	/// Designer-generated form class for MainForm.
	/// </summary>
	public partial class MainForm : IFishUIForm
	{
		#region Control Fields

		/// <summary>
		/// The Window control.
		/// </summary>
		protected Window window1;
		/// <summary>
		/// The DataGrid control.
		/// </summary>
		protected DataGrid dataGrid2;
		/// <summary>
		/// The Button control.
		/// </summary>
		protected Button BtnRefresh;

		#endregion

		/// <summary>
		/// Initializes the FishUI instance with settings.
		/// </summary>
		public void Init(FishUISettings UISettings, IFishUIGfx Gfx, IFishUIInput Input, IFishUIEvents Events)
		{
			// Override this method to customize FishUI initialization
		}

		/// <summary>
		/// Creates and configures all controls, adding them to the FishUI instance.
		/// </summary>
		public void LoadControls(FishUI.FishUI FUI)
		{
			// Create Window
			window1 = new Window();
			window1.Position = new Vector2(64f, 64f);
			window1.Size = new Vector2(576f, 464f);

			// Create DataGrid
			dataGrid2 = new DataGrid();
			dataGrid2.Position = new Vector2(16f, 16f);
			dataGrid2.Size = new Vector2(448f, 288f);
			dataGrid2.Anchor = FishUIAnchor.All;
			dataGrid2.AnchorParentSize = new Vector2(484f, 402f);

			// Add DataGrid columns
			dataGrid2.AddColumn("Column 1", 100f);
			dataGrid2.AddColumn("Column 2", 100f);

			// Create Button
			BtnRefresh = new Button();
			BtnRefresh.Position = new Vector2(16f, 352f);
			BtnRefresh.Size = new Vector2(100f, 28f);
			BtnRefresh.Anchor = FishUIAnchor.BottomLeft;
			BtnRefresh.AnchorParentSize = new Vector2(484f, 402f);
			BtnRefresh.Text = "Refresh";

			// Add children to window1
			((Window)window1).AddChild(dataGrid2);
			((Window)window1).AddChild(BtnRefresh);

			// Add root controls to FishUI
			FUI.AddControl(window1);
		}

		/// <summary>
		/// Called after all controls have been loaded. Override to add event handlers and custom logic.
		/// </summary>
		public virtual void OnLoaded()
		{
			BtnRefresh.OnButtonPressed += OnBtnRefreshClicked;
		}

		static Random Rnd = new Random();

		private void OnBtnRefreshClicked(Button Sender, FishMouseButton Btn, Vector2 Pos)
		{
			dataGrid2.AddRow(new string[] { "New Data " + Rnd.Next(), "New Data " + Rnd.Next() });
		}
	}
}
